---
- hosts: openvas
  become: true
  connection: ssh
  tasks:
    - name: Configuration du hostname
      hostname:
       name: "{{ HOSTNAME }}"

    - name: Resolution du hostname
      lineinfile:
        regexp: ^127\.0\.1\.1\s.*$
        line: "127.0.1.1 {{ HOSTNAME }} "
        path: /etc/hosts

    - name: Configurer dhclient
      lineinfile:
        regexp: ^#?prepend domain\-name\-servers .*$
        line: "prepend domain-name-servers 8.8.8.8;"
        path: /etc/dhcp/dhclient.conf
      register: dhclient_conf

    - name: Redémarrer les serveurs
      reboot:
      when: dhclient_conf.changed

    - name: Installation premiere partie des packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
          - docker.io
          - docker-compose
          - ubuntu-desktop

    - name: Recuperation du container
      shell: docker pull mikesplain/openvas

    - name: Lancement du container 
      shell: docker run -d -p 443:443 --name openvas mikesplain/openvas